name: Lint

permissions:
  contents: read

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'
  pull_request:
  workflow_call:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Open ssh debug session.'
        required: true
        default: false
        type: boolean

jobs:

  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # run static analysis on bleeding and trailing edges
        python-version: [ '3.9', '3.10', '3.13', '3.14.0-rc.3' ]

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        id: sp
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install Just
        uses: extractions/setup-just@v3
      - name: Install Dependencies
        run: |
          sudo apt-get install libopenblas-dev libxml2-dev libxslt1-dev zlib1g-dev
          just setup ${{ steps.sp.outputs.python-path }}
          just install
      - name: Install Emacs
        if: ${{ github.event.inputs.debug == 'true' }}
        run: |
          sudo apt install emacs
      - name: Setup tmate session
        if: ${{ github.event.inputs.debug == 'true' }}
        uses: mxschmitt/action-tmate@v3.22
        with:
          detached: true
        timeout-minutes: 60
      - name: Run Static Analysis
        run: |
          just check-lint
          just check-format
          just check-types
          just check-package
          just check-readme
